version: '3.9'
services:
  browser-update-controller:
    container_name: browser-update-controller
    build: ./src
    restart: unless-stopped
    env_file: .env
    ports:
      - "6001:6001"
    volumes:
      - data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6001/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 30s
volumes:
  data:
    name: browser-update-controller-data
